name: Build

on: [push, pull_request]

jobs:
  build-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - uses: actions/upload-artifact@v3
        with:
          name: script
          path: |
            public/shika.js
            public/build
        
  build-php:
    needs: build-script
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - uses: actions/download-artifact@v3
        with:
          name: script
          path: public
      
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: .
